# Generated by Django 2.2.5 on 2020-01-28 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_activate', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
                ('is_tutor', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_title', models.CharField(max_length=200)),
                ('series_summary', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(null=True, upload_to='Course_thumbnails')),
                ('price', models.IntegerField(null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Course',
            },
        ),
        migrations.CreateModel(
            name='TutorialCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_category', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('Last_name', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('Phone', models.CharField(blank=True, max_length=10)),
                ('profile_pic', models.ImageField(upload_to='profile_image')),
                ('Country', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.user_account',),
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('user_account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('Last_name', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('Phone', models.CharField(blank=True, max_length=10)),
                ('profile_pic', models.ImageField(upload_to='profile_image')),
                ('About', models.CharField(blank=True, max_length=200)),
                ('Country', models.CharField(blank=True, max_length=10)),
                ('Experience', models.CharField(blank=True, max_length=30)),
                ('Qualification', models.CharField(blank=True, max_length=20)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Instructor',
            },
            bases=('accounts.user_account',),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=100, verbose_name='Lesson Title')),
                ('video_summary', models.CharField(max_length=500, verbose_name='Lesson Description')),
                ('video_number', models.IntegerField(null=True, verbose_name='Lesson Number')),
                ('videofile', models.FileField(null=True, upload_to='videos', verbose_name='Video')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('series', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Series')),
            ],
            options={
                'verbose_name': 'Lesson',
            },
        ),
        migrations.AddField(
            model_name='series',
            name='series_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.TutorialCategory', verbose_name='Category'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=100)),
                ('question_details', models.CharField(max_length=1000, verbose_name='body')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Video')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', models.CharField(max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Question')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Referrence_Number', models.CharField(blank=True, default='5014226119', editable=False, max_length=10)),
                ('amount', models.IntegerField(blank=True)),
                ('payment_mode', models.CharField(default='Online', max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Series')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_pay', to='accounts.Student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(to='accounts.Series'),
        ),
        migrations.AddField(
            model_name='series',
            name='series_instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Tutor'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=1000)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('review_date', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Series')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student'),
        ),
    ]
